#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def load_columns(path: Path):
    rows = list(csv.DictReader(path.open("r", encoding="utf-8")))
    if not rows:
        raise ValueError(f"No rows in {path}")
    return {
        key: [float(row[key]) for row in rows]
        for key in ("episode", "anrf", "collision_percentage", "success_percentage")
    }


def save_plot(x, y, ylabel: str, output: Path) -> None:
    plt.figure(figsize=(8, 4.5))
    plt.plot(x, y)
    plt.xlabel("Episode")
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.savefig(output, dpi=180)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot metrics generated by scripts/train.py.")
    parser.add_argument("csv", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path("plots"))
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = load_columns(args.csv)
    save_plot(data["episode"], data["anrf"], "Average Normalized Reward", args.output_dir / "anrf.png")
    save_plot(data["episode"], data["collision_percentage"], "Collision Percentage (%)", args.output_dir / "collision_percentage.png")
    save_plot(data["episode"], data["success_percentage"], "Success Rate (%)", args.output_dir / "success_rate.png")
    print(f"Saved plots to {args.output_dir}")


if __name__ == "__main__":
    main()
